apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: logcleaner-role
  namespace: controller
rules:
  - apiGroups: ["stable.example.com"]
    resources: ["logcleaners"]
    verbs: ["get", "list", "watch"]
