apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: logcleaner-clusterrole
  namespace: controller
rules:
  - apiGroups: ["stable.example.com"]
    resources: ["logcleaners"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "update", "patch"]
