apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: my-controller-role
  namespace: controller
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
