apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: logcleaners.stable.example.com
spec:
  group: stable.example.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                retentionPeriod:
                  type: integer
                targetNamespace:
                  type: string
                volumeNamePattern:
                  type: string
  scope: Namespaced
  names:
    plural: logcleaners
    singular: logcleaner
    kind: LogCleaner
    shortNames:
      - lc
