apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-store-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
  volumeName: log-store-pv
