apiVersion: v1
kind: PersistentVolume
metadata:
  name: log-store-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 10Gi
  storageClassName: standard
  hostPath:
    path: /tmp/log-store-pv
